### ISSUE TITLE
docs: Inputs is nothing in export-secrets

### ISSUE THREAD

**Issue by sshota0809** [suzuki-shunsuke/tfaction#132]
Hello, thank you for creating awesome tool.

This is minor misprint I noticed when I read source code.

# ACTUAL

* export-secrets
The `secrets` parameter is required  while nothing is required in README.

https://github.com/suzuki-shunsuke/tfaction/blob/5118f1de57a70c3914f5654b2c08cfcdbca6e493/export-secrets/action.yaml#L4-L6

https://github.com/suzuki-shunsuke/tfaction/blob/5118f1de57a70c3914f5654b2c08cfcdbca6e493/export-secrets/README.md?plain=1#L17-L19

# EXPECTED BEHAVIOR

The `secrets` parameter is required  also in README.

I will create PR against this issue. Thank you.

**Comment by suzuki-shunsuke** [comment]
Fixed by #133

Thank you for your contribution!
