### ISSUE TITLE
tfaction doesn't support releasing modules that is more than 2+ level of directories

### ISSUE THREAD

**Issue by kyontan** [suzuki-shunsuke/tfaction#1398]
### tfaction version

v0.7.3

### Overview

`suzuki-shunsuke/tfaction/release-module` action provides feature to release terraform module.

https://github.com/suzuki-shunsuke/tfaction/tree/main/release-module

Though, if the module source is under 2+ levels of directory, it tags with `/` character included.
e.g.
- module source: `modules/some-module/nested`
- created tag (by tfaction): `module_some-module/nested_vX.Y.Z`

Since terraform doesn't handle `/` in the reference name (git tag), it fails during `terraform init`.

### How to reproduce

described above.

There's no error in tfaction, but unconfortable.

### Expected behaviour

All the shashes (`/`) appeared in the module path should be replaced to `/`.

e.g.
- module source: `modules/some-module/nested`
- created tag (by tfaction): `module_some-module_nested_vX.Y.Z`

### Actual behaviour

e.g.
- module source: `modules/some-module/nested`
- created tag (by tfaction): `module_some-module/nested_vX.Y.Z`

### Important Factoids

This is because shell's regexp replacement supports replacement only one occurence.

https://github.com/suzuki-shunsuke/tfaction/blob/857d2bd9cdf1cf54993b0f80784dc5741db15b65/release-module/action.yaml#L39

We should use `sed` or alternative to replace multiple occurences.

### Reference

*

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.

**Comment by suzuki-shunsuke** [comment]
We're planning to release v1 on the next Monday. https://github.com/suzuki-shunsuke/tfaction/pull/1291
After releasing v1, we will take a look at this issue.
The workaround is to use 1 level directory simply.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction/pull/1407

**Comment by suzuki-shunsuke** [comment]
v1.0.1 is out 🎉
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.0.1
