### ISSUE TITLE
Consider migration from Jest to Vitest

### ISSUE THREAD

**Issue by exoego** [suzuki-shunsuke/tfaction#1591]
As a contributor, it would be nice if tests run fast.

[Vitest](https://vitest.dev/) is a very fast test framework becoming popular in JS world in the recent years.
I've recently migrated my work projects from Jest to Vitest and the team are quite happy with the results.

- Fast. In my work projects, migrating to Vitest halves test time (40 seconds -> 20 seconds)
- Jest compatible. Even many Jest plugins run with Vitest.
- Compact. Its bundle size is 51 KB compared to Jest's 582 KB.
- Out-of-box TypeScript support

You can see the visualized comparison in https://moiva.io/?npm=jest+vitest

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
I'm not familiar with Vitest, but it looks nice!

**Comment by suzuki-shunsuke** [comment]
📝 https://vitest.dev/guide/migration.html#migrating-from-jest
