### ISSUE TITLE
contest runs even if skip label is added

### ISSUE THREAD

**Issue by florianmutter** [suzuki-shunsuke/tfaction#1935]
### tfaction version

1.11.0

### Overview

When the `skip:...` label is added no plan is created. the conftest step still runs and does not find the plan and therefor fails with the error 

```
Error: running test: parse files: get file info: stat tfplan.json: no such file or directory
```

### How to reproduce

tfaction-root.yaml

```yaml

```

tfaction.yaml

```yaml

```

GitHub Actions Workflow

```yaml

```

Other related code such as local Registry

```

```

GitHub Actions' log

```
```

### Expected behaviour

Only run conftest in plan mode if skip label is not added.

### Actual behaviour

conftest runs despite skip label added

**Comment by suzuki-shunsuke** [comment]
Thank you for reporting this issue!
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction/pull/1936

**Comment by suzuki-shunsuke** [comment]
v1.11.1 is out 🎉
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.11.1
