### ISSUE TITLE
Feature Request: Allow config_path as input for trivy-config-action in tfaction/test

### ISSUE THREAD

**Issue by falcon-tech** [suzuki-shunsuke/tfaction#2165]
### Feature Overview

Allow config_path as input for trivy-config-action in tfaction/test

https://github.com/suzuki-shunsuke/tfaction/blob/main/test/action.yaml#L46-L51

### Why is the feature needed?

Currently, when calling trivy-config-action from tfaction/test, there is no option to specify the config_path as an input value. This limits the flexibility of configuring Trivy for different use cases.

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.1.1

You can specify Trivy's configuration file path by the environment variable `TRIVY_CONFIG` in GitHub Actions Workflows.

```yaml
env:
  TRIVY_CONFIG: ${{ github.workspace }}/trivy.yaml
```

**Comment by falcon-tech** [comment]
Sorry! I missed the release notes. Thank you very much for the notice!
