### ISSUE TITLE
Question: Is the absence of a fix flag in the inputs of "github-action-tflint" when called from the "test-module" intentional by design?

### ISSUE THREAD

**Issue by falcon-tech** [suzuki-shunsuke/tfaction#2175]
### Question

The "github-action-tflint" called in "[test-module](https://github.com/suzuki-shunsuke/tfaction/blob/main/test-module/action.yaml)" does not have a fix flag in its inputs, whereas the one called in "[test](https://github.com/suzuki-shunsuke/tfaction/blob/main/test/action.yaml)" does include a fix flag.

### Call github-action-tflint in test-module
![image](https://github.com/user-attachments/assets/35674396-42d6-4c47-934f-c191f5214021)

### Call github-action-tflint in test
![image](https://github.com/user-attachments/assets/417bdd3d-b20f-416b-9bc0-1c1486dbe963)

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
I don't think it's design.
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction/pull/2176

**Comment by falcon-tech** [comment]
Thank you for the quick fix!

**Comment by suzuki-shunsuke** [comment]
🎉 https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.14.0
