### ISSUE TITLE
Old tfplan.binary is not deleted in GCS when terraform plan fails

### ISSUE THREAD

**Issue by sshota0809** [suzuki-shunsuke/tfaction#252]
Hi! I found thing that seems like bug.

https://github.com/suzuki-shunsuke/tfaction/blob/de7ecacfad625cf6ccdc823e3f8f177dca8b2a22/terraform-plan/main.sh#L12-L16

In action `terrafom-plan`, when terraform plan fails old `tfplan.binary` is supposed to be deleted in case of S3. But it remains in case of GCS.

Is this a behavior you suppose? If not, I'm going to make PR.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
Yes. This is a bug.
I'll really appreciate if you send a pull request.

**Comment by sshota0809** [comment]
Thank you for response! I'm going to send the PR tomorrow. Please wait a while.

**Comment by suzuki-shunsuke** [comment]
Released https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.4
