### ISSUE TITLE
skip_create_pr.sh is always executed when terraform apply fails regardless of skip_create_pr option

### ISSUE THREAD

**Issue by sshota0809** [suzuki-shunsuke/tfaction#256]
Hi, I found a thing like a bag.

# ACTUAL

Even if the `skip_create_pr` option (default: `false`) is set both `false` or `true` in `tfaction-root.yaml`, `skip_create_pr.sh` is always executed when terraform apply fails.

https://github.com/suzuki-shunsuke/tfaction/blob/c779fe438bd153662c440599f2a5be361033293a/create-follow-up-pr/action.yaml#L18

# EXPECTED

When `skip_create_pr` option is set as `false`, `main.sh` is executed not but `skip_create_pr.sh`.

https://github.com/suzuki-shunsuke/tfaction/blob/c779fe438bd153662c440599f2a5be361033293a/create-follow-up-pr/action.yaml#L27

# MY RESEARCH

This bug is caused by the following wrong condition.

https://github.com/suzuki-shunsuke/tfaction/blob/c779fe438bd153662c440599f2a5be361033293a/create-follow-up-pr/action.yaml#L18-L33

According to [this document](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context), `output` is always dealt as `string` so it can't compare to boolean.

In above case, as long as `steps.global-config.outputs.skip_create_pr` is not null, the result of condition is always `true`.

Refference: [GitHub Actions で真偽値を正しく扱う](https://note.sarisia.cc/entry/boolean-in-github-actions/)

I'm going to send PR!

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!
Please send a pull request 🙏

**Comment by suzuki-shunsuke** [comment]
```console
$ git grep "if:"
.github/workflows/apply.yaml:    if: "join(fromJSON(needs.setup.outputs.tfmigrate_targets), '') != ''"
.github/workflows/apply.yaml:        if: failure()
.github/workflows/apply.yaml:    if: "join(fromJSON(needs.setup.outputs.terraform_targets), '') != ''"
.github/workflows/apply.yaml:        if: failure()
.github/workflows/deploy-schema.yaml:      if: github.event_name != 'pull_request'
.github/workflows/test.yaml:    if: "join(fromJSON(needs.setup.outputs.tfmigrate_targets), '') != ''"
.github/workflows/test.yaml:    if: "join(fromJSON(needs.setup.outputs.terraform_targets), '') != ''"
.github/workflows/test.yaml:    if: failure()
create-follow-up-pr/action.yaml:      if: steps.global-config.outputs.skip_create_pr
create-follow-up-pr/action.yaml:      if: '! steps.global-config.outputs.skip_create_pr'
create-scaffold-pr/action.yaml:      if: steps.global-config.outputs.skip_create_pr
create-scaffold-pr/action.yaml:      if: '! steps.global-config.outputs.skip_create_pr'
list-targets-with-changed-files/dist/index.js:    getSarif: ["GET /repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}"],
list-targets-with-changed-files/dist/index.js:    uploadSarif: ["POST /repos/{owner}/{repo}/code-scanning/sarifs"]
list-targets-with-changed-files/dist/index.js:  // istanbul ignore if: should never happen
release-module/action.yaml:      if: inputs.module_path == ''
release-module/action.yaml:      if: inputs.version == ''
scaffold-module/action.yaml:      if: inputs.github_token == ''
scaffold-module/action.yaml:      if: inputs.module_path == ''
scaffold-module/action.yaml:      if: steps.global-config.outputs.skip_create_pr
scaffold-module/action.yaml:      if: '! steps.global-config.outputs.skip_create_pr'
scaffold-tfmigrate/action.yaml:      if: steps.global-config.outputs.skip_create_pr
scaffold-tfmigrate/action.yaml:      if: '! steps.global-config.outputs.skip_create_pr'
scaffold-tfmigrate/action.yaml:      if: '! steps.global-config.outputs.skip_create_pr'
setup/action.yaml:      if: github.event_name == 'pull_request'
setup/action.yaml:      if: steps.target-config.outputs.aws_assume_role_arn != ''
setup/action.yaml:      if: steps.target-config.outputs.gcp_service_account != ''
setup/action.yaml:      if: inputs.ssh_key != ''
terraform-apply/action.yaml:      if: "!fromJSON(steps.check-terraform-skip.outputs.skip_terraform)"
terraform-plan/action.yaml:      if: "!fromJSON(steps.check-terraform-skip.outputs.skip_terraform)"
```

The same bugs are included in the following files.

* create-follow-up-pr/action.yaml
* scaffold-module/action.yaml
* scaffold-tfmigrate/action.yaml

On the other hand, it looks correct.

```
terraform-plan/action.yaml:      if: "!fromJSON(steps.check-terraform-skip.outputs.skip_terraform)"
```

**Comment by sshota0809** [comment]
@suzuki-shunsuke 
My PR is based on comparing with string, but as you said this looks good. I fixed the conditions like following!
```
terraform-plan/action.yaml:      if: "!fromJSON(steps.check-terraform-skip.outputs.skip_terraform)"
```

**Comment by sshota0809** [comment]
@suzuki-shunsuke 
I'm sorry we just missed each other! I send new PR related to this comment.
https://github.com/suzuki-shunsuke/tfaction/issues/256#issuecomment-1061361218

**Comment by suzuki-shunsuke** [comment]
I'm sorry but I missed your comment. Please send a pull request again.
Thank you.

**Comment by suzuki-shunsuke** [comment]
[v0.5.5](https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.5) has been released!
Thank you for your contribution!
