### ISSUE TITLE
Perhaps tfaction-root.yaml overwrites tfaction.yaml in working directory

### ISSUE THREAD

**Issue by sshota0809** [suzuki-shunsuke/tfaction#261]
Hi, I found kind of like a bug.

# ACTUAL

https://suzuki-shunsuke.github.io/tfaction/docs/config/tfaction-yaml

In above document, It seems that `tfaction.yaml` in working directory overwrites `tfaction-root.yaml`.

```
You can override the configuration of tfaction-root.yaml by tfaction.yaml.
```

On the other hand, in the action `get-target-config` it seems that `tfaction-root.yaml` overwrites `tfaction.yaml` in working directory.

https://github.com/suzuki-shunsuke/tfaction/blob/4f6e115706b6060fa0d56e7674d32ff7098d62f4/get-target-config/src/index.ts#L41-L52

As far as I read the codes, each variables mean like following.

* jobConfig: terraform_(plan|apply)_config in tfaction.yaml
* wdConfig: tfaction.yaml
* rootJobConfig: terraform_(plan|apply)_config in matched target in tfaction-root.yaml
* targetConfig: matched target in tfaction-root.yaml
* config: tfaction-root.yaml

So the order of list in arguments to `setOutputs` seems incorrect.

# EXPECTED

The order like following is correct?

```
    lib.setOutputs([
      's3_bucket_name_plan_file',
      's3_bucket_name_tfmigrate_history',
      'gcs_bucket_name_plan_file',
      'providers_lock_opts',
    ], [config, targetConfig, wdConfig]);
    lib.setOutputs([
      'aws_region',
      'aws_assume_role_arn',
      'gcp_service_account',
      'gcp_workload_identity_provider',
    ], [config, targetConfig, rootJobConfig, wdConfig, jobConfig]);
```

If it's correct I send the PR! Thank you for reading in advance.

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/tfaction/blob/c636652c893a8c3e96f6b3e5f469fac573b850ee/get-target-config/src/lib.ts#L104-L115

I think the order is correct, but if you find it doesn't work as the document, please let us know.

**Comment by sshota0809** [comment]
Thank you for your reply.

I missed `break;` keyword. I apologize I bothered you, I close this issue.
