### ISSUE TITLE
Proposal: being able to add any terraform options to `terraform plan / apply` makes more flexibility

### ISSUE THREAD

**Issue by sshota0809** [suzuki-shunsuke/tfaction#311]
Hi, This is my proposal.

I want to try to make pipeline with tfaction faster adding the `-parallelism=n` option to `terraform plan / apply`.
What if `terraform-plan` and `terraform-apply` actions support adding any terraform options to realize this? What do you think of this.

If it seems good idea, I will create the PR.

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

How about setting environment variables?

https://www.terraform.io/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name

```
TF_CLI_ARGS_plan="-parallelism=30"
TF_CLI_ARGS_apply="-parallelism=30"
```

**Comment by sshota0809** [comment]
Thank you for your response.

I've never heard of this way to set options through environment variables. It seems great. I'm thinking of creating a PR that allows to set options through an input of GitHub Actions that is set as `env` like following.

https://github.com/suzuki-shunsuke/tfaction/blob/3bae240250c79bb63b87385b12b86bb981f89716/terraform-plan/action.yaml#L3-L6
https://github.com/suzuki-shunsuke/tfaction/blob/3bae240250c79bb63b87385b12b86bb981f89716/terraform-plan/action.yaml#L29-L35

What do you think of it?

**Comment by suzuki-shunsuke** [comment]
I think we don't have to add inputs.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv

e.g.

```console
- uses: suzuki-shunsuke/tfaction/terraform-apply@main
  with:
    github_app_token: ${{ steps.generate_token.outputs.token }}
  env:
    TF_CLI_ARGS_apply: "-parallelism=30"
```

**Comment by sshota0809** [comment]
I understand, this is the best way without any modification. Thanks a lot for your advice!

I'll close this issue.
