### ISSUE TITLE
Make terraform option configureble by tfaction.yml

### ISSUE THREAD

**Issue by kyontan** [suzuki-shunsuke/tfaction#420]
Hi, this is feature request for tfaction!

We are managing a lot of working directories, and I'm facing a problem like https://github.com/hashicorp/terraform-provider-aws/issues/5171 .
To prevent this problem, I want to pass `[--parallelism](https://www.terraform.io/docs/commands/plan.html#parallelism-n)` flag to the terraform command, but currently it's not possible.

I'm thinking about adding configuration item to `tfaction.yaml` like:

```
terraform-option: --parallelism 10
```

And this is passed to https://github.com/suzuki-shunsuke/tfaction/blob/49635435837a90431435bbe0f3c18c0460a82366/terraform-plan/main.sh#L8 .

Thanks in advance!

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
You can set options with environment variables.
https://github.com/suzuki-shunsuke/tfaction/issues/311#issuecomment-1109267034

https://suzuki-shunsuke.github.io/tfaction/docs/config/terraform-cli-options

**Comment by kyontan** [comment]
@suzuki-shunsuke Thanks for your quick reply!
That's what I wanted and I missed 🙇 

Thanks!

**Comment by kyontan** [comment]
@suzuki-shunsuke 
By the way, it's preferable to be able to set the environment variables thorough `tfaction.yaml`.
Since I want to set the `TF_CLI_ARGS` only in a few working directories, it'd be great if it's easy to configure per working directory basis.
Anyway, we can configure this behavior by tweaking workflow and read some config file and pass the environment variable to plan / apply action, but it's a little complexed.

How do you think?

**Comment by suzuki-shunsuke** [comment]
It makes sense.

e.g.

tfaction.yaml

```yaml
env:
  TF_CLI_ARGS_plan: "-parallelism=30"
```

**Comment by suzuki-shunsuke** [comment]
Please try https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.13-0

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.13

**Comment by kyontan** [comment]
Thank you! I'll introduce it to our repo soon 🚀
