### ISSUE TITLE
Run conftest on tfmigrate-plan

### ISSUE THREAD

**Issue by kyontan** [suzuki-shunsuke/tfaction#511]
Hi, this is a some kind of bug report, and feature request.

I noticed that the `conftest` validation doesn't run during `tfmigrate-plan` action.
We noticed that the resource definition violating our conftest policy in `terraform-plan` after tfmigrate'd.

I think this part in `terraform-plan` should also be in `tfmigrate-plan`.
https://github.com/suzuki-shunsuke/tfaction/blob/91916f7cf7d2df7f8a01357f5d15e07a603d0555/terraform-plan/main.sh#L30-L38

Furthermore, there's a edge case related to this: `skip:` prefix used in tfmgirate multi-state migration.
If a working directory that was added resources skipped `tfmigrate-plan` by `skip:xxx` label, this would cause an issue.
To fix the case, I propose splitting build matrix from [`terraform`, `tfmigrate`] to [`terraform`, `tfmigrate`, `conftest (or validation)`].  What do you think?

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

I understood your problem.

> I propose splitting build matrix from [terraform, tfmigrate] to [terraform, tfmigrate, conftest (or validation)]. What do you think?

`conftest` is run against terraform's plan file.
`tfmigrate` doesn't create a plan file, so we have to run `terraform plan` and `conftest` apart from `tfmigrate`.
But if we run `terraform plan`, the result is different from `terraform plan` tfmigrate runs internally, because the result of state migration isn't reflected.
So the result of conftest may be unexpected.

**Comment by kyontan** [comment]
> But if we run terraform plan, the result is different from terraform plan tfmigrate runs internally, because the result of state migration isn't reflected.
> So the result of conftest may be unexpected.

Ah, I forget about that, that's right.
Since it's difficult (or no way) to get `plan.json` before `terraform plan`, I understood its difficulty.

Can we change conftest target from `plan.json` to hcl directly?
It seems conftest supports it.
https://www.conftest.dev/examples/

**Comment by suzuki-shunsuke** [comment]
> Can we change conftest target from plan.json to hcl directly?

I guess conftest can't evaluate Terraform expression (local value, input variables, functions, resource and module attributes, etc).

> tfmigrate doesn't create a plan file

I'm sorry but this may be wrong.
I verified the following ways to create a plan file with tfmigrate.

1. tfmigrate plan's `--out` option
1. [Terraform's environment variable `TF_CLI_ARGS_plan`](https://www.terraform.io/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name)

## 1. tfmigrate plan's `--out` option

I've confirmed it works well, but this option is deprecated.

https://github.com/minamijoyo/tfmigrate/commit/dba98a641d958ac7b1e87eee219d560a8ab22fcd

Actually, the plan file can't be used for apply, but can be used for conftest.
But this option would be removed and we should avoid to use deprecated option.

## 2. Terraform's environment variable `TF_CLI_ARGS_plan`

I expected we can pass `terraform plan` option to `tfmigrate plan` with `TF_CLI_ARGS_plan`.

```console
$ env TF_CLI_ARGS_plan="-out=tfplan.out $TF_CLI_ARGS_plan" tfmigrate plan
```

But unfortunately plan file isn't created. I don't know why... 🤔

This approach is recommended by the author of tfmigrate, so it should work.
https://github.com/minamijoyo/tfmigrate/issues/27#issuecomment-858211424

**Comment by suzuki-shunsuke** [comment]
Reported the issue.

- https://github.com/minamijoyo/tfmigrate/issues/106

**Comment by suzuki-shunsuke** [comment]
I understood why `TF_CLI_ARGS_plan="-out=tfplan.out` doesn't work.
https://github.com/minamijoyo/tfmigrate/issues/106#issuecomment-1243826555

**Comment by suzuki-shunsuke** [comment]
tfmigrate has reverted the deprecation of the tfmigrate plan --out=tfplan option.

- https://github.com/minamijoyo/tfmigrate/issues/106#issuecomment-1246495788

So we can fix `tfmigrate-plan` to run conftest.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction/pull/516

**Comment by suzuki-shunsuke** [comment]
Published the prerelease version v0.5.18-0. https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.18-0
We'll release v0.5.18 in few days.
We'll really appreciate if you try the prerelease version before releasing v0.5.18.
Thanks.

**Comment by kyontan** [comment]
Thanks for your great work!
I'll try the new version.

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.18
