### ISSUE TITLE
Support configuring environment variables per target

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#95]
```yaml
env:
  <env name>: <env value>
  # ...
```

**Comment by florianmutter** [comment]
We would like to use that but the same way secrets can beused: pulling variables from github action variables.

**Comment by suzuki-shunsuke** [comment]
This issue has been resolved already.
You can set the environment variables per target by `tfaction-root.yaml` and `tfaction.yaml`.

- https://github.com/suzuki-shunsuke/tfaction/pull/421

I'll update the document, then close this issue.

https://suzuki-shunsuke.github.io/tfaction/docs/config/tfaction-root-yaml
https://suzuki-shunsuke.github.io/tfaction/docs/config/tfaction-yaml

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction-docs/pull/221

**Comment by suzuki-shunsuke** [comment]
@florianmutter

> We would like to use that but the same way secrets can beused: pulling variables from github action variables.

Thank you for your proposal.
Your proposal is out of the scope of this issue, so please create a new discussion.
